import type { Locale } from "@/i18n/routing";

export type CoopContent = {
  metaTitle: string;
  metaDescription: string;
  adjacent: string;
  tagline: string;
  intro: string;
  experimental: string;
  explore: string;
  viewSource: string;
  quickStart: string;
  facts: string[];
  appLibrary: string;
  worker: string;
  sharedProviders: string;
  onePerMachine: string;
  diagramAria: string;
  whyTitle: string;
  whyBody: string;
  perryTitle: string;
  perryBody: string;
  coopTitle: string;
  coopBody: string;
  architectureTitle: string;
  architectureBody: string;
  tiers: Array<{ title: string; body: string }>;
  workingTitle: string;
  workingBody: string;
  workingItems: string[];
  developerTitle: string;
  developerBody: string;
  configLabel: string;
  handlerLabel: string;
  runLabel: string;
  fitTitle: string;
  rightTitle: string;
  rightItems: string[];
  notYetTitle: string;
  notYetItems: string[];
  benchmarkTitle: string;
  benchmarkBody: string;
  benchmarks: string;
  status: string;
  closingTitle: string;
  closingBody: string;
};

const content: Record<Locale, CoopContent> = {
  en: {
    metaTitle: "Coop — Native TypeScript hosting for Perry",
    metaDescription: "Coop hosts TypeScript applications compiled by Perry, with shared runtime providers, isolated deployment workers, and content-addressed rollbacks.",
    adjacent: "Perry-adjacent project · Pre-1.0",
    tagline: "A place for Perry code to rest and run.",
    intro: "Coop turns a directory of Perry-compatible TypeScript into a native application library and serves it over HTTP, while the Perry runtime and standard library are supplied once per machine.",
    experimental: "Experimental infrastructure for code you own",
    explore: "Explore Coop",
    viewSource: "View source",
    quickStart: "Quick start",
    facts: ["Shared runtime providers", "One worker per deployment", "Deploy, inspect, and roll back"],
    appLibrary: "App library",
    worker: "Coop worker",
    sharedProviders: "Shared runtime + standard library",
    onePerMachine: "one per machine",
    diagramAria: "TypeScript is compiled by Perry into an application library, loaded by a Coop worker, and connected to shared runtime providers.",
    whyTitle: "Perry compiles it. Coop keeps it running.",
    whyBody: "The distinction is where the language runtime lives. Coop keeps the application image small and supplies the compatible Perry runtime and standard library at the host level.",
    perryTitle: "A regular Perry executable",
    perryBody: "The application, runtime, garbage collector, and selected standard-library features are linked into one target-specific executable.",
    coopTitle: "A Coop deployment",
    coopBody: "The application is compiled as an app-only shared library. Compatible runtime providers are built once per machine, and their identity is verified before the app is mapped.",
    architectureTitle: "Split by failure boundary",
    architectureBody: "The box, each deployment, and each request have separate responsibilities. Application code never runs in the box daemon.",
    tiers: [
      { title: "Daemon · one per machine", body: "Terminates TLS, routes by host and path, owns deployments, artifacts, the admin API, and metrics." },
      { title: "Worker · one per deployment", body: "Loads the application library, owns Perry runtime state, and runs cron and durable queue work." },
      { title: "Invocation · one per request", body: "Runs as a task inside the deployment worker, sharing its address space without spawning a process per request." },
    ],
    workingTitle: "What works today",
    workingBody: "Coop is tested infrastructure, but it is not yet a finished hosting product. The current implementation includes:",
    workingItems: ["TypeScript compilation, HTTP routing, and static mounts", "Shared provider identity checks", "Content-addressed deployments and rollback", "Cron and a durable queue", "Dedicated-worker KV and object storage", "CLI, Prometheus metrics, alerts, and a Grafana dashboard"],
    developerTitle: "A small deployment surface",
    developerBody: "A deployment is a directory with a coop.toml file and one or more handlers. Coop compiles it, caches the result, and starts a local worker.",
    configLabel: "coop.toml",
    handlerLabel: "handlers/hello.ts",
    runLabel: "Run locally",
    fitTitle: "Deliberately narrow",
    rightTitle: "A good fit today",
    rightItems: ["Services and small applications whose code you own", "One operator running a portfolio on one machine", "Workloads that compile within Perry's TypeScript subset", "Teams that value density, explicit artifacts, and fast rollback"],
    notYetTitle: "Not a promise Coop makes yet",
    notYetItems: ["Arbitrary npm or Node.js compatibility", "A sandbox for untrusted third-party code", "A Kubernetes replacement or multi-region platform", "Universal performance wins over Node.js"],
    benchmarkTitle: "Density is the thesis. Benchmarks are still the work.",
    benchmarkBody: "Current measurements point in different directions on different workloads. Coop has shown promising density on small Linux applications, while a full Next.js route has cost more CPU than Node.js in another test. Read the methodology before quoting either result.",
    benchmarks: "Read the benchmarks",
    status: "See current status",
    closingTitle: "Build with Perry. Give it a Coop.",
    closingBody: "Explore the source, run the example deployment, and help turn the shared-runtime model into dependable infrastructure.",
  },
  de: {
    metaTitle: "Coop — Natives TypeScript-Hosting für Perry",
    metaDescription: "Coop hostet mit Perry kompilierte TypeScript-Anwendungen mit gemeinsam genutzten Laufzeitbibliotheken, isolierten Deployment-Workern und inhaltsadressierten Rollbacks.",
    adjacent: "Perry-nahes Projekt · Pre-1.0",
    tagline: "Ein Ort, an dem Perry-Code ruhen und laufen kann.",
    intro: "Coop verwandelt ein Verzeichnis mit Perry-kompatiblem TypeScript in eine native Anwendungsbibliothek und stellt sie über HTTP bereit. Perry-Laufzeit und Standardbibliothek werden dabei nur einmal pro Maschine bereitgestellt.",
    experimental: "Experimentelle Infrastruktur für eigenen Code",
    explore: "Coop entdecken",
    viewSource: "Quellcode ansehen",
    quickStart: "Schnellstart",
    facts: ["Gemeinsam genutzte Laufzeitbibliotheken", "Ein Worker pro Deployment", "Deployen, prüfen und zurückrollen"],
    appLibrary: "Anwendungsbibliothek",
    worker: "Coop-Worker",
    sharedProviders: "Gemeinsame Laufzeit + Standardbibliothek",
    onePerMachine: "einmal pro Maschine",
    diagramAria: "TypeScript wird von Perry zu einer Anwendungsbibliothek kompiliert, von einem Coop-Worker geladen und mit gemeinsam genutzten Laufzeitbibliotheken verbunden.",
    whyTitle: "Perry kompiliert. Coop hält es am Laufen.",
    whyBody: "Der Unterschied liegt darin, wo die Sprachlaufzeit lebt. Coop hält das Anwendungsabbild klein und stellt die kompatible Perry-Laufzeit samt Standardbibliothek auf Host-Ebene bereit.",
    perryTitle: "Ein reguläres Perry-Programm",
    perryBody: "Anwendung, Laufzeit, Garbage Collector und ausgewählte Funktionen der Standardbibliothek werden in eine zielspezifische ausführbare Datei gelinkt.",
    coopTitle: "Ein Coop-Deployment",
    coopBody: "Die Anwendung wird als reine App-Bibliothek kompiliert. Kompatible Laufzeitbibliotheken werden einmal pro Maschine gebaut und ihre Identität vor dem Einbinden der App geprüft.",
    architectureTitle: "Nach Fehlergrenzen getrennt",
    architectureBody: "Maschine, Deployment und Anfrage haben getrennte Verantwortlichkeiten. Anwendungscode läuft niemals im Box-Daemon.",
    tiers: [
      { title: "Daemon · einer pro Maschine", body: "Beendet TLS, routet nach Host und Pfad und verwaltet Deployments, Artefakte, Admin-API und Metriken." },
      { title: "Worker · einer pro Deployment", body: "Lädt die Anwendungsbibliothek, besitzt den Perry-Laufzeitzustand und führt Cron- sowie dauerhafte Queue-Aufgaben aus." },
      { title: "Aufruf · einer pro Anfrage", body: "Läuft als Task im Deployment-Worker und teilt dessen Adressraum, ohne pro Anfrage einen Prozess zu starten." },
    ],
    workingTitle: "Was heute funktioniert",
    workingBody: "Coop ist getestete Infrastruktur, aber noch kein fertiges Hosting-Produkt. Die aktuelle Implementierung umfasst:",
    workingItems: ["TypeScript-Kompilierung, HTTP-Routing und statische Mounts", "Identitätsprüfungen für gemeinsame Provider", "Inhaltsadressierte Deployments und Rollback", "Cron und eine dauerhafte Queue", "KV- und Objektspeicher für dedizierte Worker", "CLI, Prometheus-Metriken, Alarme und Grafana-Dashboard"],
    developerTitle: "Eine kleine Deployment-Oberfläche",
    developerBody: "Ein Deployment ist ein Verzeichnis mit einer coop.toml-Datei und einem oder mehreren Handlern. Coop kompiliert es, speichert das Ergebnis im Cache und startet einen lokalen Worker.",
    configLabel: "coop.toml",
    handlerLabel: "handlers/hello.ts",
    runLabel: "Lokal ausführen",
    fitTitle: "Bewusst eng gefasst",
    rightTitle: "Heute gut geeignet für",
    rightItems: ["Dienste und kleine Anwendungen mit eigenem Code", "Einen Betreiber mit einem Portfolio auf einer Maschine", "Workloads innerhalb von Perrys TypeScript-Teilmenge", "Teams, die Dichte, explizite Artefakte und schnelle Rollbacks schätzen"],
    notYetTitle: "Was Coop noch nicht verspricht",
    notYetItems: ["Beliebige npm- oder Node.js-Kompatibilität", "Eine Sandbox für nicht vertrauenswürdigen Drittcode", "Kubernetes-Ersatz oder Multi-Region-Plattform", "Universelle Performance-Vorteile gegenüber Node.js"],
    benchmarkTitle: "Dichte ist die These. Benchmarks bleiben die Arbeit.",
    benchmarkBody: "Aktuelle Messungen zeigen je nach Workload in unterschiedliche Richtungen. Kleine Linux-Anwendungen zeigen vielversprechende Dichte, während eine vollständige Next.js-Route in einem anderen Test mehr CPU als Node.js benötigte. Vor dem Zitieren bitte die Methodik lesen.",
    benchmarks: "Benchmarks lesen",
    status: "Aktuellen Status ansehen",
    closingTitle: "Mit Perry bauen. In Coop laufen lassen.",
    closingBody: "Quellcode erkunden, das Beispiel-Deployment starten und helfen, das Shared-Runtime-Modell zu verlässlicher Infrastruktur zu machen.",
  },
  es: {
    metaTitle: "Coop — Alojamiento de TypeScript nativo para Perry",
    metaDescription: "Coop aloja aplicaciones TypeScript compiladas por Perry con proveedores de runtime compartidos, workers de despliegue aislados y rollbacks direccionados por contenido.",
    adjacent: "Proyecto cercano a Perry · Pre-1.0",
    tagline: "Un lugar donde el código de Perry puede descansar y ejecutarse.",
    intro: "Coop convierte un directorio de TypeScript compatible con Perry en una biblioteca de aplicación nativa y la sirve por HTTP, mientras el runtime y la biblioteca estándar de Perry se proporcionan una sola vez por máquina.",
    experimental: "Infraestructura experimental para código propio",
    explore: "Explorar Coop",
    viewSource: "Ver código fuente",
    quickStart: "Inicio rápido",
    facts: ["Proveedores de runtime compartidos", "Un worker por despliegue", "Desplegar, inspeccionar y revertir"],
    appLibrary: "Biblioteca de la aplicación",
    worker: "Worker de Coop",
    sharedProviders: "Runtime + biblioteca estándar compartidos",
    onePerMachine: "uno por máquina",
    diagramAria: "Perry compila TypeScript en una biblioteca de aplicación, un worker de Coop la carga y la conecta con proveedores de runtime compartidos.",
    whyTitle: "Perry lo compila. Coop lo mantiene en marcha.",
    whyBody: "La diferencia está en dónde vive el runtime del lenguaje. Coop mantiene pequeña la imagen de la aplicación y proporciona el runtime compatible de Perry y la biblioteca estándar en el host.",
    perryTitle: "Un ejecutable Perry normal",
    perryBody: "La aplicación, el runtime, el recolector de basura y las funciones elegidas de la biblioteca estándar se enlazan en un ejecutable específico para el destino.",
    coopTitle: "Un despliegue Coop",
    coopBody: "La aplicación se compila como una biblioteca compartida que solo contiene la app. Los proveedores compatibles se construyen una vez por máquina y su identidad se verifica antes de mapearla.",
    architectureTitle: "Separado por límites de fallo",
    architectureBody: "La máquina, cada despliegue y cada petición tienen responsabilidades distintas. El código de la aplicación nunca se ejecuta en el daemon de la máquina.",
    tiers: [
      { title: "Daemon · uno por máquina", body: "Termina TLS, enruta por host y ruta, y gestiona despliegues, artefactos, la API de administración y métricas." },
      { title: "Worker · uno por despliegue", body: "Carga la biblioteca de la aplicación, mantiene el estado del runtime de Perry y ejecuta cron y colas duraderas." },
      { title: "Invocación · una por petición", body: "Se ejecuta como tarea dentro del worker y comparte su espacio de direcciones sin crear un proceso por petición." },
    ],
    workingTitle: "Lo que funciona hoy",
    workingBody: "Coop es infraestructura probada, pero aún no es un producto de alojamiento terminado. La implementación actual incluye:",
    workingItems: ["Compilación TypeScript, enrutamiento HTTP y montajes estáticos", "Comprobaciones de identidad de proveedores compartidos", "Despliegues direccionados por contenido y rollback", "Cron y una cola duradera", "KV y almacenamiento de objetos para workers dedicados", "CLI, métricas Prometheus, alertas y panel de Grafana"],
    developerTitle: "Una superficie de despliegue pequeña",
    developerBody: "Un despliegue es un directorio con coop.toml y uno o más handlers. Coop lo compila, guarda el resultado en caché e inicia un worker local.",
    configLabel: "coop.toml",
    handlerLabel: "handlers/hello.ts",
    runLabel: "Ejecutar localmente",
    fitTitle: "Deliberadamente limitado",
    rightTitle: "Una buena opción hoy",
    rightItems: ["Servicios y aplicaciones pequeñas cuyo código controlas", "Un operador que ejecuta una cartera en una máquina", "Cargas que compilan dentro del subconjunto TypeScript de Perry", "Equipos que valoran densidad, artefactos explícitos y rollback rápido"],
    notYetTitle: "Lo que Coop todavía no promete",
    notYetItems: ["Compatibilidad arbitraria con npm o Node.js", "Un sandbox para código de terceros no confiable", "Sustituir Kubernetes o ser una plataforma multirregión", "Mejoras universales de rendimiento frente a Node.js"],
    benchmarkTitle: "La densidad es la tesis. Los benchmarks siguen siendo el trabajo.",
    benchmarkBody: "Las mediciones actuales apuntan en direcciones distintas según la carga. Coop ha mostrado una densidad prometedora con aplicaciones Linux pequeñas, mientras una ruta Next.js completa consumió más CPU que Node.js en otra prueba. Lee la metodología antes de citar los resultados.",
    benchmarks: "Leer los benchmarks",
    status: "Ver estado actual",
    closingTitle: "Construye con Perry. Dale un Coop.",
    closingBody: "Explora el código, ejecuta el despliegue de ejemplo y ayuda a convertir el modelo de runtime compartido en infraestructura fiable.",
  },
  fr: {
    metaTitle: "Coop — Hébergement TypeScript natif pour Perry",
    metaDescription: "Coop héberge des applications TypeScript compilées par Perry avec des runtimes partagés, des workers de déploiement isolés et des restaurations adressées par contenu.",
    adjacent: "Projet adjacent à Perry · Pré-1.0",
    tagline: "Un endroit où le code Perry peut se poser et s'exécuter.",
    intro: "Coop transforme un dossier TypeScript compatible avec Perry en bibliothèque d'application native et la sert en HTTP, tandis que le runtime et la bibliothèque standard de Perry ne sont fournis qu'une fois par machine.",
    experimental: "Infrastructure expérimentale pour votre propre code",
    explore: "Découvrir Coop",
    viewSource: "Voir le code source",
    quickStart: "Démarrage rapide",
    facts: ["Runtimes fournisseurs partagés", "Un worker par déploiement", "Déployer, inspecter et restaurer"],
    appLibrary: "Bibliothèque d'application",
    worker: "Worker Coop",
    sharedProviders: "Runtime + bibliothèque standard partagés",
    onePerMachine: "un par machine",
    diagramAria: "Perry compile TypeScript en bibliothèque d'application, chargée par un worker Coop et reliée aux runtimes partagés.",
    whyTitle: "Perry compile. Coop maintient en ligne.",
    whyBody: "La différence tient à l'emplacement du runtime du langage. Coop garde l'image applicative légère et fournit le runtime Perry compatible et la bibliothèque standard au niveau de l'hôte.",
    perryTitle: "Un exécutable Perry classique",
    perryBody: "L'application, le runtime, le ramasse-miettes et les fonctions choisies de la bibliothèque standard sont liés dans un exécutable propre à la cible.",
    coopTitle: "Un déploiement Coop",
    coopBody: "L'application est compilée comme une bibliothèque partagée ne contenant que l'app. Les fournisseurs compatibles sont construits une fois par machine et leur identité est vérifiée avant son chargement.",
    architectureTitle: "Séparé par limite de défaillance",
    architectureBody: "La machine, chaque déploiement et chaque requête ont des responsabilités distinctes. Le code applicatif ne s'exécute jamais dans le daemon de la machine.",
    tiers: [
      { title: "Daemon · un par machine", body: "Termine TLS, route par hôte et chemin, et gère les déploiements, artefacts, l'API d'administration et les métriques." },
      { title: "Worker · un par déploiement", body: "Charge la bibliothèque applicative, possède l'état du runtime Perry et exécute les tâches cron et de file durable." },
      { title: "Invocation · une par requête", body: "S'exécute comme tâche dans le worker et partage son espace d'adressage sans créer un processus par requête." },
    ],
    workingTitle: "Ce qui fonctionne aujourd'hui",
    workingBody: "Coop est une infrastructure testée, mais pas encore un produit d'hébergement finalisé. L'implémentation actuelle comprend :",
    workingItems: ["Compilation TypeScript, routage HTTP et montages statiques", "Contrôles d'identité des fournisseurs partagés", "Déploiements adressés par contenu et restauration", "Cron et file durable", "KV et stockage d'objets pour workers dédiés", "CLI, métriques Prometheus, alertes et tableau de bord Grafana"],
    developerTitle: "Une surface de déploiement réduite",
    developerBody: "Un déploiement est un dossier contenant coop.toml et un ou plusieurs handlers. Coop le compile, met le résultat en cache et démarre un worker local.",
    configLabel: "coop.toml",
    handlerLabel: "handlers/hello.ts",
    runLabel: "Exécuter localement",
    fitTitle: "Volontairement ciblé",
    rightTitle: "Un bon choix aujourd'hui",
    rightItems: ["Services et petites applications dont vous possédez le code", "Un opérateur gérant un portefeuille sur une machine", "Charges compilables dans le sous-ensemble TypeScript de Perry", "Équipes privilégiant densité, artefacts explicites et restauration rapide"],
    notYetTitle: "Ce que Coop ne promet pas encore",
    notYetItems: ["Compatibilité arbitraire avec npm ou Node.js", "Sandbox pour du code tiers non fiable", "Remplacement de Kubernetes ou plateforme multirégion", "Gains de performances universels face à Node.js"],
    benchmarkTitle: "La densité est la thèse. Les benchmarks restent le travail.",
    benchmarkBody: "Les mesures actuelles divergent selon la charge. Coop a montré une densité prometteuse sur de petites applications Linux, tandis qu'une route Next.js complète a consommé plus de CPU que Node.js dans un autre test. Lisez la méthodologie avant de citer ces résultats.",
    benchmarks: "Lire les benchmarks",
    status: "Voir l'état actuel",
    closingTitle: "Construisez avec Perry. Donnez-lui un Coop.",
    closingBody: "Explorez le code source, lancez le déploiement d'exemple et contribuez à rendre fiable le modèle de runtime partagé.",
  },
  it: {
    metaTitle: "Coop — Hosting TypeScript nativo per Perry",
    metaDescription: "Coop ospita applicazioni TypeScript compilate da Perry con runtime condivisi, worker di deployment isolati e rollback indirizzati dal contenuto.",
    adjacent: "Progetto adiacente a Perry · Pre-1.0",
    tagline: "Un posto dove il codice Perry può riposare ed essere eseguito.",
    intro: "Coop trasforma una directory di TypeScript compatibile con Perry in una libreria applicativa nativa e la serve via HTTP, fornendo runtime e libreria standard di Perry una sola volta per macchina.",
    experimental: "Infrastruttura sperimentale per codice di tua proprietà",
    explore: "Scopri Coop",
    viewSource: "Vedi il sorgente",
    quickStart: "Guida rapida",
    facts: ["Runtime provider condivisi", "Un worker per deployment", "Distribuisci, ispeziona e ripristina"],
    appLibrary: "Libreria applicativa",
    worker: "Worker Coop",
    sharedProviders: "Runtime + libreria standard condivisi",
    onePerMachine: "uno per macchina",
    diagramAria: "Perry compila TypeScript in una libreria applicativa, caricata da un worker Coop e collegata ai runtime condivisi.",
    whyTitle: "Perry compila. Coop mantiene in esecuzione.",
    whyBody: "La differenza è dove risiede il runtime del linguaggio. Coop mantiene piccola l'immagine applicativa e fornisce il runtime Perry compatibile e la libreria standard a livello host.",
    perryTitle: "Un normale eseguibile Perry",
    perryBody: "Applicazione, runtime, garbage collector e funzioni selezionate della libreria standard vengono collegati in un eseguibile specifico per il target.",
    coopTitle: "Un deployment Coop",
    coopBody: "L'applicazione viene compilata come libreria condivisa contenente solo l'app. I provider compatibili vengono costruiti una volta per macchina e la loro identità è verificata prima del mapping.",
    architectureTitle: "Separato per confine di errore",
    architectureBody: "Macchina, deployment e richiesta hanno responsabilità distinte. Il codice applicativo non viene mai eseguito nel daemon della macchina.",
    tiers: [
      { title: "Daemon · uno per macchina", body: "Termina TLS, instrada per host e percorso e gestisce deployment, artefatti, API amministrativa e metriche." },
      { title: "Worker · uno per deployment", body: "Carica la libreria applicativa, possiede lo stato del runtime Perry ed esegue cron e code durevoli." },
      { title: "Invocazione · una per richiesta", body: "Viene eseguita come task nel worker e ne condivide lo spazio di indirizzamento senza creare un processo per richiesta." },
    ],
    workingTitle: "Cosa funziona oggi",
    workingBody: "Coop è infrastruttura testata, ma non ancora un prodotto di hosting completo. L'implementazione attuale include:",
    workingItems: ["Compilazione TypeScript, routing HTTP e mount statici", "Controlli di identità dei provider condivisi", "Deployment indirizzati dal contenuto e rollback", "Cron e coda durevole", "KV e object storage per worker dedicati", "CLI, metriche Prometheus, alert e dashboard Grafana"],
    developerTitle: "Una superficie di deployment ridotta",
    developerBody: "Un deployment è una directory con coop.toml e uno o più handler. Coop la compila, mette il risultato in cache e avvia un worker locale.",
    configLabel: "coop.toml",
    handlerLabel: "handlers/hello.ts",
    runLabel: "Esegui in locale",
    fitTitle: "Volutamente ristretto",
    rightTitle: "Adatto oggi a",
    rightItems: ["Servizi e piccole applicazioni di cui possiedi il codice", "Un operatore con un portafoglio su una macchina", "Carichi che compilano nel sottoinsieme TypeScript di Perry", "Team che apprezzano densità, artefatti espliciti e rollback rapido"],
    notYetTitle: "Cosa Coop non promette ancora",
    notYetItems: ["Compatibilità arbitraria con npm o Node.js", "Sandbox per codice terzo non attendibile", "Sostituto di Kubernetes o piattaforma multi-regione", "Vantaggi prestazionali universali su Node.js"],
    benchmarkTitle: "La densità è la tesi. I benchmark restano il lavoro.",
    benchmarkBody: "Le misure attuali vanno in direzioni diverse a seconda del carico. Coop ha mostrato una densità promettente su piccole app Linux, mentre una route Next.js completa ha usato più CPU di Node.js in un altro test. Leggi la metodologia prima di citare i risultati.",
    benchmarks: "Leggi i benchmark",
    status: "Vedi lo stato attuale",
    closingTitle: "Costruisci con Perry. Dagli un Coop.",
    closingBody: "Esplora il sorgente, avvia il deployment di esempio e contribuisci a rendere affidabile il modello di runtime condiviso.",
  },
  ja: {
    metaTitle: "Coop — Perry向けネイティブTypeScriptホスティング",
    metaDescription: "Coopは、共有ランタイム、分離されたデプロイワーカー、コンテンツアドレス方式のロールバックで、PerryがコンパイルしたTypeScriptアプリをホストします。",
    adjacent: "Perry隣接プロジェクト · Pre-1.0",
    tagline: "Perryコードが休み、動ける場所。",
    intro: "CoopはPerry互換のTypeScriptディレクトリをネイティブアプリライブラリに変換してHTTPで配信し、Perryランタイムと標準ライブラリをマシンごとに一度だけ提供します。",
    experimental: "自分で所有するコード向けの実験的インフラ",
    explore: "Coopを見る",
    viewSource: "ソースを見る",
    quickStart: "クイックスタート",
    facts: ["共有ランタイムプロバイダー", "デプロイごとに1ワーカー", "デプロイ、確認、ロールバック"],
    appLibrary: "アプリライブラリ",
    worker: "Coopワーカー",
    sharedProviders: "共有ランタイム + 標準ライブラリ",
    onePerMachine: "マシンごとに1つ",
    diagramAria: "TypeScriptをPerryがアプリライブラリへコンパイルし、Coopワーカーが読み込み、共有ランタイムへ接続します。",
    whyTitle: "Perryがコンパイルし、Coopが動かし続けます。",
    whyBody: "違いは言語ランタイムの置き場所です。Coopはアプリイメージを小さく保ち、互換性のあるPerryランタイムと標準ライブラリをホスト側で提供します。",
    perryTitle: "通常のPerry実行ファイル",
    perryBody: "アプリ、ランタイム、ガベージコレクター、選択した標準ライブラリ機能を、対象ごとの1つの実行ファイルへリンクします。",
    coopTitle: "Coopデプロイ",
    coopBody: "アプリのみの共有ライブラリとしてコンパイルします。互換プロバイダーはマシンごとに一度ビルドされ、アプリをマップする前にその同一性が検証されます。",
    architectureTitle: "障害境界で分離",
    architectureBody: "マシン、各デプロイ、各リクエストの責任を分けます。アプリコードがマシンのデーモン内で動くことはありません。",
    tiers: [
      { title: "デーモン · マシンごとに1つ", body: "TLS終端、ホストとパスによるルーティング、デプロイ、成果物、管理API、メトリクスを担当します。" },
      { title: "ワーカー · デプロイごとに1つ", body: "アプリライブラリを読み込み、Perryランタイム状態を所有し、cronと永続キューを実行します。" },
      { title: "呼び出し · リクエストごとに1つ", body: "デプロイワーカー内のタスクとして動き、リクエストごとにプロセスを作らずアドレス空間を共有します。" },
    ],
    workingTitle: "現在動作するもの",
    workingBody: "Coopはテスト済みのインフラですが、完成したホスティング製品ではありません。現在の実装には次が含まれます。",
    workingItems: ["TypeScriptコンパイル、HTTPルーティング、静的マウント", "共有プロバイダーの同一性チェック", "コンテンツアドレス方式のデプロイとロールバック", "cronと永続キュー", "専用ワーカー向けKVとオブジェクトストレージ", "CLI、Prometheusメトリクス、アラート、Grafanaダッシュボード"],
    developerTitle: "小さなデプロイ構成",
    developerBody: "デプロイはcoop.tomlと1つ以上のハンドラーを含むディレクトリです。Coopがコンパイルして結果をキャッシュし、ローカルワーカーを起動します。",
    configLabel: "coop.toml",
    handlerLabel: "handlers/hello.ts",
    runLabel: "ローカル実行",
    fitTitle: "意図的に狭い対象",
    rightTitle: "現在適している用途",
    rightItems: ["自分で所有するコードのサービスや小規模アプリ", "1台のマシンでポートフォリオを運用する1人の管理者", "PerryのTypeScriptサブセットでコンパイルできるワークロード", "密度、明示的な成果物、高速ロールバックを重視するチーム"],
    notYetTitle: "まだ約束していないこと",
    notYetItems: ["任意のnpmやNode.jsとの互換性", "信頼できない第三者コード向けサンドボックス", "Kubernetesの代替やマルチリージョンプラットフォーム", "Node.jsに対する普遍的な性能優位"],
    benchmarkTitle: "密度が仮説。ベンチマークは進行中です。",
    benchmarkBody: "現在の測定結果はワークロードによって方向が異なります。小規模Linuxアプリでは有望な密度を示した一方、別のテストでは完全なNext.jsルートがNode.jsより多くのCPUを使用しました。引用前に手法を確認してください。",
    benchmarks: "ベンチマークを読む",
    status: "現在の状態を見る",
    closingTitle: "Perryで作り、Coopで動かす。",
    closingBody: "ソースを調べ、サンプルデプロイを動かし、共有ランタイムモデルを信頼できるインフラへ育ててください。",
  },
  ko: {
    metaTitle: "Coop — Perry용 네이티브 TypeScript 호스팅",
    metaDescription: "Coop은 공유 런타임 공급자, 격리된 배포 워커, 콘텐츠 주소 기반 롤백으로 Perry가 컴파일한 TypeScript 앱을 호스팅합니다.",
    adjacent: "Perry 인접 프로젝트 · Pre-1.0",
    tagline: "Perry 코드가 쉬고 실행되는 곳.",
    intro: "Coop은 Perry 호환 TypeScript 디렉터리를 네이티브 앱 라이브러리로 만들고 HTTP로 제공하며, Perry 런타임과 표준 라이브러리는 머신마다 한 번만 제공합니다.",
    experimental: "직접 소유한 코드를 위한 실험적 인프라",
    explore: "Coop 살펴보기",
    viewSource: "소스 보기",
    quickStart: "빠른 시작",
    facts: ["공유 런타임 공급자", "배포마다 하나의 워커", "배포, 점검, 롤백"],
    appLibrary: "앱 라이브러리",
    worker: "Coop 워커",
    sharedProviders: "공유 런타임 + 표준 라이브러리",
    onePerMachine: "머신마다 하나",
    diagramAria: "Perry가 TypeScript를 앱 라이브러리로 컴파일하고 Coop 워커가 이를 로드해 공유 런타임 공급자에 연결합니다.",
    whyTitle: "Perry가 컴파일하고 Coop이 계속 실행합니다.",
    whyBody: "차이는 언어 런타임이 어디에 있는가입니다. Coop은 앱 이미지를 작게 유지하고 호스트 수준에서 호환 Perry 런타임과 표준 라이브러리를 제공합니다.",
    perryTitle: "일반 Perry 실행 파일",
    perryBody: "앱, 런타임, 가비지 컬렉터, 선택한 표준 라이브러리 기능을 대상별 실행 파일 하나에 링크합니다.",
    coopTitle: "Coop 배포",
    coopBody: "앱만 담은 공유 라이브러리로 컴파일합니다. 호환 공급자는 머신마다 한 번 빌드되며 앱을 매핑하기 전에 그 신원이 검증됩니다.",
    architectureTitle: "장애 경계로 분리",
    architectureBody: "머신, 각 배포, 각 요청의 책임을 나눕니다. 앱 코드는 머신 데몬 안에서 실행되지 않습니다.",
    tiers: [
      { title: "데몬 · 머신마다 하나", body: "TLS 종료, 호스트와 경로 라우팅, 배포, 아티팩트, 관리 API와 메트릭을 담당합니다." },
      { title: "워커 · 배포마다 하나", body: "앱 라이브러리를 로드하고 Perry 런타임 상태를 소유하며 cron과 내구성 큐 작업을 실행합니다." },
      { title: "호출 · 요청마다 하나", body: "배포 워커 내부의 태스크로 실행되어 요청마다 프로세스를 만들지 않고 주소 공간을 공유합니다." },
    ],
    workingTitle: "현재 동작하는 기능",
    workingBody: "Coop은 테스트된 인프라이지만 아직 완성된 호스팅 제품은 아닙니다. 현재 구현에는 다음이 포함됩니다.",
    workingItems: ["TypeScript 컴파일, HTTP 라우팅, 정적 마운트", "공유 공급자 신원 검사", "콘텐츠 주소 기반 배포와 롤백", "cron과 내구성 큐", "전용 워커용 KV와 객체 스토리지", "CLI, Prometheus 메트릭, 알림, Grafana 대시보드"],
    developerTitle: "작은 배포 구성",
    developerBody: "배포는 coop.toml과 하나 이상의 핸들러가 있는 디렉터리입니다. Coop이 컴파일하고 결과를 캐시한 뒤 로컬 워커를 시작합니다.",
    configLabel: "coop.toml",
    handlerLabel: "handlers/hello.ts",
    runLabel: "로컬에서 실행",
    fitTitle: "의도적으로 좁은 범위",
    rightTitle: "현재 잘 맞는 경우",
    rightItems: ["직접 소유한 코드의 서비스와 소규모 앱", "한 머신에서 포트폴리오를 운영하는 한 명의 운영자", "Perry의 TypeScript 하위 집합에서 컴파일되는 워크로드", "밀도, 명시적 아티팩트, 빠른 롤백을 중시하는 팀"],
    notYetTitle: "아직 약속하지 않는 것",
    notYetItems: ["임의의 npm 또는 Node.js 호환성", "신뢰할 수 없는 제3자 코드를 위한 샌드박스", "Kubernetes 대체 또는 멀티 리전 플랫폼", "Node.js보다 항상 빠르다는 보장"],
    benchmarkTitle: "밀도가 가설이며, 벤치마크는 진행 중입니다.",
    benchmarkBody: "현재 측정은 워크로드에 따라 서로 다른 방향을 보입니다. 작은 Linux 앱에서는 유망한 밀도를 보였지만 다른 테스트의 전체 Next.js 라우트는 Node.js보다 CPU를 더 사용했습니다. 결과를 인용하기 전에 방법론을 확인하세요.",
    benchmarks: "벤치마크 읽기",
    status: "현재 상태 보기",
    closingTitle: "Perry로 만들고 Coop에서 실행하세요.",
    closingBody: "소스를 살펴보고 예제 배포를 실행하며 공유 런타임 모델을 신뢰할 수 있는 인프라로 만드는 데 참여하세요.",
  },
  pt: {
    metaTitle: "Coop — Hospedagem TypeScript nativa para Perry",
    metaDescription: "Coop hospeda aplicações TypeScript compiladas pelo Perry com runtimes compartilhados, workers de implantação isolados e rollbacks endereçados por conteúdo.",
    adjacent: "Projeto adjacente ao Perry · Pré-1.0",
    tagline: "Um lugar para o código Perry descansar e rodar.",
    intro: "Coop transforma um diretório de TypeScript compatível com Perry em uma biblioteca de aplicação nativa e a serve por HTTP, enquanto o runtime e a biblioteca padrão do Perry são fornecidos uma única vez por máquina.",
    experimental: "Infraestrutura experimental para código próprio",
    explore: "Explorar o Coop",
    viewSource: "Ver código-fonte",
    quickStart: "Início rápido",
    facts: ["Runtimes compartilhados", "Um worker por implantação", "Implantar, inspecionar e reverter"],
    appLibrary: "Biblioteca da aplicação",
    worker: "Worker do Coop",
    sharedProviders: "Runtime + biblioteca padrão compartilhados",
    onePerMachine: "um por máquina",
    diagramAria: "Perry compila TypeScript em uma biblioteca de aplicação, carregada por um worker do Coop e conectada aos runtimes compartilhados.",
    whyTitle: "Perry compila. Coop mantém rodando.",
    whyBody: "A diferença está em onde o runtime da linguagem vive. Coop mantém a imagem da aplicação pequena e fornece o runtime compatível do Perry e a biblioteca padrão no host.",
    perryTitle: "Um executável Perry normal",
    perryBody: "Aplicação, runtime, coletor de lixo e recursos selecionados da biblioteca padrão são ligados em um executável específico para o destino.",
    coopTitle: "Uma implantação Coop",
    coopBody: "A aplicação é compilada como biblioteca compartilhada contendo apenas o app. Runtimes compatíveis são construídos uma vez por máquina e sua identidade é verificada antes do mapeamento.",
    architectureTitle: "Separado por limite de falha",
    architectureBody: "A máquina, cada implantação e cada requisição têm responsabilidades distintas. O código da aplicação nunca roda no daemon da máquina.",
    tiers: [
      { title: "Daemon · um por máquina", body: "Termina TLS, roteia por host e caminho e gerencia implantações, artefatos, API administrativa e métricas." },
      { title: "Worker · um por implantação", body: "Carrega a biblioteca, mantém o estado do runtime Perry e executa cron e filas duráveis." },
      { title: "Invocação · uma por requisição", body: "Roda como tarefa dentro do worker e compartilha seu espaço de endereçamento sem criar um processo por requisição." },
    ],
    workingTitle: "O que funciona hoje",
    workingBody: "Coop é infraestrutura testada, mas ainda não é um produto de hospedagem concluído. A implementação atual inclui:",
    workingItems: ["Compilação TypeScript, roteamento HTTP e montagens estáticas", "Verificações de identidade dos runtimes compartilhados", "Implantações endereçadas por conteúdo e rollback", "Cron e fila durável", "KV e armazenamento de objetos para workers dedicados", "CLI, métricas Prometheus, alertas e painel Grafana"],
    developerTitle: "Uma superfície de implantação pequena",
    developerBody: "Uma implantação é um diretório com coop.toml e um ou mais handlers. Coop compila, armazena o resultado em cache e inicia um worker local.",
    configLabel: "coop.toml",
    handlerLabel: "handlers/hello.ts",
    runLabel: "Executar localmente",
    fitTitle: "Deliberadamente focado",
    rightTitle: "Uma boa opção hoje",
    rightItems: ["Serviços e pequenas aplicações cujo código é seu", "Um operador executando um portfólio em uma máquina", "Cargas que compilam no subconjunto TypeScript do Perry", "Equipes que valorizam densidade, artefatos explícitos e rollback rápido"],
    notYetTitle: "O que o Coop ainda não promete",
    notYetItems: ["Compatibilidade arbitrária com npm ou Node.js", "Sandbox para código de terceiros não confiável", "Substituir Kubernetes ou ser plataforma multirregião", "Ganhos universais de desempenho sobre Node.js"],
    benchmarkTitle: "Densidade é a tese. Benchmarks ainda são o trabalho.",
    benchmarkBody: "As medições atuais apontam em direções diferentes conforme a carga. Coop mostrou densidade promissora em pequenas aplicações Linux, enquanto uma rota Next.js completa usou mais CPU que Node.js em outro teste. Leia a metodologia antes de citar os resultados.",
    benchmarks: "Ler os benchmarks",
    status: "Ver status atual",
    closingTitle: "Construa com Perry. Dê um Coop a ele.",
    closingBody: "Explore o código, execute a implantação de exemplo e ajude a tornar o modelo de runtime compartilhado uma infraestrutura confiável.",
  },
  th: {
    metaTitle: "Coop — โฮสติ้ง TypeScript แบบเนทีฟสำหรับ Perry",
    metaDescription: "Coop โฮสต์แอป TypeScript ที่คอมไพล์ด้วย Perry โดยใช้รันไทม์ร่วมกัน เวิร์กเกอร์แยกต่อการดีพลอย และการย้อนกลับแบบอ้างอิงเนื้อหา",
    adjacent: "โปรเจกต์ข้างเคียง Perry · Pre-1.0",
    tagline: "ที่พักและที่รันสำหรับโค้ด Perry",
    intro: "Coop เปลี่ยนไดเรกทอรี TypeScript ที่เข้ากับ Perry ให้เป็นไลบรารีแอปแบบเนทีฟและให้บริการผ่าน HTTP โดยมีรันไทม์และไลบรารีมาตรฐานของ Perry เพียงชุดเดียวต่อเครื่อง",
    experimental: "โครงสร้างพื้นฐานทดลองสำหรับโค้ดที่คุณเป็นเจ้าของ",
    explore: "สำรวจ Coop",
    viewSource: "ดูซอร์สโค้ด",
    quickStart: "เริ่มต้นอย่างรวดเร็ว",
    facts: ["ผู้ให้บริการรันไทม์ร่วมกัน", "หนึ่งเวิร์กเกอร์ต่อการดีพลอย", "ดีพลอย ตรวจสอบ และย้อนกลับ"],
    appLibrary: "ไลบรารีแอป",
    worker: "เวิร์กเกอร์ Coop",
    sharedProviders: "รันไทม์ + ไลบรารีมาตรฐานร่วมกัน",
    onePerMachine: "หนึ่งต่อเครื่อง",
    diagramAria: "Perry คอมไพล์ TypeScript เป็นไลบรารีแอป จากนั้นเวิร์กเกอร์ Coop โหลดและเชื่อมต่อกับรันไทม์ที่ใช้ร่วมกัน",
    whyTitle: "Perry คอมไพล์ ส่วน Coop ดูแลให้รันต่อไป",
    whyBody: "ความแตกต่างอยู่ที่ตำแหน่งของรันไทม์ภาษา Coop ทำให้อิมเมจแอปมีขนาดเล็กและจัดหารันไทม์ Perry ที่เข้ากันได้พร้อมไลบรารีมาตรฐานในระดับโฮสต์",
    perryTitle: "ไฟล์รัน Perry แบบปกติ",
    perryBody: "แอป รันไทม์ ตัวเก็บขยะ และส่วนที่เลือกของไลบรารีมาตรฐานจะถูกลิงก์เป็นไฟล์รันเฉพาะเป้าหมายเดียว",
    coopTitle: "การดีพลอย Coop",
    coopBody: "แอปถูกคอมไพล์เป็นไลบรารีร่วมที่มีเฉพาะตัวแอป ผู้ให้บริการที่เข้ากันได้ถูกสร้างหนึ่งครั้งต่อเครื่องและตรวจสอบตัวตนก่อนแมปแอป",
    architectureTitle: "แยกตามขอบเขตความล้มเหลว",
    architectureBody: "เครื่อง การดีพลอยแต่ละชุด และคำขอแต่ละรายการมีหน้าที่แยกกัน โค้ดแอปจะไม่รันในดีมอนของเครื่อง",
    tiers: [
      { title: "ดีมอน · หนึ่งต่อเครื่อง", body: "ยุติ TLS จัดเส้นทางตามโฮสต์และพาธ และดูแลการดีพลอย อาร์ติแฟกต์ API ผู้ดูแล และเมตริก" },
      { title: "เวิร์กเกอร์ · หนึ่งต่อการดีพลอย", body: "โหลดไลบรารีแอป ดูแลสถานะรันไทม์ Perry และรันงาน cron กับคิวแบบทนทาน" },
      { title: "การเรียก · หนึ่งต่อคำขอ", body: "รันเป็นงานภายในเวิร์กเกอร์และใช้พื้นที่แอดเดรสร่วมกันโดยไม่สร้างโปรเซสใหม่ต่อคำขอ" },
    ],
    workingTitle: "สิ่งที่ใช้งานได้วันนี้",
    workingBody: "Coop เป็นโครงสร้างพื้นฐานที่ผ่านการทดสอบ แต่ยังไม่ใช่ผลิตภัณฑ์โฮสติ้งที่เสร็จสมบูรณ์ การทำงานปัจจุบันประกอบด้วย:",
    workingItems: ["คอมไพล์ TypeScript จัดเส้นทาง HTTP และเมานต์ไฟล์สแตติก", "ตรวจสอบตัวตนของรันไทม์ร่วม", "ดีพลอยแบบอ้างอิงเนื้อหาและย้อนกลับ", "cron และคิวแบบทนทาน", "KV และที่เก็บอ็อบเจกต์สำหรับเวิร์กเกอร์เฉพาะ", "CLI เมตริก Prometheus การแจ้งเตือน และแดชบอร์ด Grafana"],
    developerTitle: "พื้นผิวการดีพลอยที่เล็ก",
    developerBody: "การดีพลอยคือไดเรกทอรีที่มี coop.toml และแฮนด์เลอร์อย่างน้อยหนึ่งตัว Coop จะคอมไพล์ แคชผลลัพธ์ และเริ่มเวิร์กเกอร์ในเครื่อง",
    configLabel: "coop.toml",
    handlerLabel: "handlers/hello.ts",
    runLabel: "รันในเครื่อง",
    fitTitle: "ขอบเขตแคบโดยตั้งใจ",
    rightTitle: "เหมาะกับงานวันนี้",
    rightItems: ["บริการและแอปขนาดเล็กที่คุณเป็นเจ้าของโค้ด", "ผู้ดูแลหนึ่งรายที่รันหลายบริการบนเครื่องเดียว", "งานที่คอมไพล์ได้ในชุดย่อย TypeScript ของ Perry", "ทีมที่ให้ความสำคัญกับความหนาแน่น อาร์ติแฟกต์ชัดเจน และการย้อนกลับเร็ว"],
    notYetTitle: "สิ่งที่ Coop ยังไม่รับประกัน",
    notYetItems: ["ความเข้ากันได้กับ npm หรือ Node.js ทุกแพ็กเกจ", "แซนด์บ็อกซ์สำหรับโค้ดบุคคลที่สามที่ไม่น่าเชื่อถือ", "การแทน Kubernetes หรือแพลตฟอร์มหลายภูมิภาค", "ประสิทธิภาพเหนือ Node.js ในทุกงาน"],
    benchmarkTitle: "ความหนาแน่นคือสมมติฐาน ส่วนเบนช์มาร์กยังอยู่ระหว่างการทำงาน",
    benchmarkBody: "ผลวัดปัจจุบันต่างกันตามลักษณะงาน Coop แสดงความหนาแน่นที่ดีในแอป Linux ขนาดเล็ก แต่อีกการทดสอบหนึ่งพบว่าเส้นทาง Next.js เต็มรูปแบบใช้ CPU มากกว่า Node.js โปรดอ่านวิธีการก่อนอ้างผล",
    benchmarks: "อ่านเบนช์มาร์ก",
    status: "ดูสถานะปัจจุบัน",
    closingTitle: "สร้างด้วย Perry แล้วให้ Coop ดูแล",
    closingBody: "สำรวจซอร์ส รันตัวอย่างการดีพลอย และช่วยพัฒนาโมเดลรันไทม์ร่วมให้เป็นโครงสร้างพื้นฐานที่เชื่อถือได้",
  },
  tr: {
    metaTitle: "Coop — Perry için yerel TypeScript barındırma",
    metaDescription: "Coop, Perry ile derlenen TypeScript uygulamalarını paylaşılan çalışma zamanı sağlayıcıları, yalıtılmış dağıtım worker'ları ve içerik adresli geri dönüşlerle barındırır.",
    adjacent: "Perry'ye komşu proje · Pre-1.0",
    tagline: "Perry kodunun dinlenip çalışabileceği bir yer.",
    intro: "Coop, Perry uyumlu bir TypeScript dizinini yerel uygulama kitaplığına dönüştürüp HTTP üzerinden sunar; Perry çalışma zamanı ve standart kitaplık ise makine başına yalnızca bir kez sağlanır.",
    experimental: "Sahibi olduğunuz kod için deneysel altyapı",
    explore: "Coop'u keşfet",
    viewSource: "Kaynak kodu gör",
    quickStart: "Hızlı başlangıç",
    facts: ["Paylaşılan çalışma zamanı sağlayıcıları", "Dağıtım başına bir worker", "Dağıt, incele ve geri al"],
    appLibrary: "Uygulama kitaplığı",
    worker: "Coop worker",
    sharedProviders: "Paylaşılan çalışma zamanı + standart kitaplık",
    onePerMachine: "makine başına bir",
    diagramAria: "TypeScript, Perry tarafından uygulama kitaplığına derlenir; Coop worker bunu yükler ve paylaşılan çalışma zamanı sağlayıcılarına bağlar.",
    whyTitle: "Perry derler. Coop çalışır tutar.",
    whyBody: "Fark, dil çalışma zamanının nerede yaşadığıdır. Coop uygulama imajını küçük tutar ve uyumlu Perry çalışma zamanı ile standart kitaplığı host düzeyinde sağlar.",
    perryTitle: "Normal bir Perry çalıştırılabilir dosyası",
    perryBody: "Uygulama, çalışma zamanı, çöp toplayıcı ve seçilen standart kitaplık özellikleri hedefe özgü tek bir çalıştırılabilir dosyaya bağlanır.",
    coopTitle: "Bir Coop dağıtımı",
    coopBody: "Uygulama yalnızca app içeren paylaşılan kitaplık olarak derlenir. Uyumlu sağlayıcılar makine başına bir kez oluşturulur ve app eşlenmeden önce kimlikleri doğrulanır.",
    architectureTitle: "Hata sınırına göre ayrılmış",
    architectureBody: "Makine, her dağıtım ve her istek ayrı sorumluluklara sahiptir. Uygulama kodu makine daemon'unda asla çalışmaz.",
    tiers: [
      { title: "Daemon · makine başına bir", body: "TLS'i sonlandırır; host ve yola göre yönlendirir; dağıtımları, artefaktları, yönetim API'sini ve metrikleri yönetir." },
      { title: "Worker · dağıtım başına bir", body: "Uygulama kitaplığını yükler, Perry çalışma zamanı durumunu sahiplenir ve cron ile kalıcı kuyruk işlerini çalıştırır." },
      { title: "Çağrı · istek başına bir", body: "Dağıtım worker'ı içinde görev olarak çalışır ve istek başına süreç başlatmadan adres alanını paylaşır." },
    ],
    workingTitle: "Bugün çalışanlar",
    workingBody: "Coop test edilmiş bir altyapıdır ancak henüz tamamlanmış bir barındırma ürünü değildir. Güncel uygulama şunları içerir:",
    workingItems: ["TypeScript derleme, HTTP yönlendirme ve statik bağlama", "Paylaşılan sağlayıcı kimlik kontrolleri", "İçerik adresli dağıtımlar ve geri dönüş", "Cron ve kalıcı kuyruk", "Özel worker'lar için KV ve nesne depolama", "CLI, Prometheus metrikleri, alarmlar ve Grafana panosu"],
    developerTitle: "Küçük bir dağıtım yüzeyi",
    developerBody: "Dağıtım, coop.toml ve bir veya daha fazla handler içeren dizindir. Coop bunu derler, sonucu önbelleğe alır ve yerel worker başlatır.",
    configLabel: "coop.toml",
    handlerLabel: "handlers/hello.ts",
    runLabel: "Yerelde çalıştır",
    fitTitle: "Bilinçli olarak dar",
    rightTitle: "Bugün iyi uyduğu yerler",
    rightItems: ["Koduna sahip olduğunuz servisler ve küçük uygulamalar", "Tek makinede portföy çalıştıran tek operatör", "Perry'nin TypeScript alt kümesinde derlenen iş yükleri", "Yoğunluk, açık artefaktlar ve hızlı geri dönüşe önem veren ekipler"],
    notYetTitle: "Coop'un henüz vaat etmedikleri",
    notYetItems: ["Her npm veya Node.js paketiyle uyumluluk", "Güvenilmeyen üçüncü taraf kodu için sandbox", "Kubernetes alternatifi veya çok bölgeli platform", "Node.js'e karşı evrensel performans kazancı"],
    benchmarkTitle: "Yoğunluk tezdir. Benchmark çalışması sürüyor.",
    benchmarkBody: "Güncel ölçümler iş yüküne göre farklı yönleri gösteriyor. Coop küçük Linux uygulamalarında umut verici yoğunluk sağlarken başka bir testte tam Next.js rotası Node.js'ten fazla CPU kullandı. Sonuçları alıntılamadan önce metodolojiyi okuyun.",
    benchmarks: "Benchmark'ları oku",
    status: "Güncel durumu gör",
    closingTitle: "Perry ile üret. Coop'ta çalıştır.",
    closingBody: "Kaynağı keşfedin, örnek dağıtımı çalıştırın ve paylaşılan çalışma zamanı modelini güvenilir altyapıya dönüştürmeye yardımcı olun.",
  },
  vi: {
    metaTitle: "Coop — Lưu trữ TypeScript native cho Perry",
    metaDescription: "Coop lưu trữ ứng dụng TypeScript được Perry biên dịch với runtime dùng chung, worker triển khai tách biệt và rollback định địa chỉ theo nội dung.",
    adjacent: "Dự án liền kề Perry · Pre-1.0",
    tagline: "Nơi mã Perry có thể nghỉ và chạy.",
    intro: "Coop biến một thư mục TypeScript tương thích với Perry thành thư viện ứng dụng native và phục vụ qua HTTP, trong khi runtime và thư viện chuẩn Perry chỉ được cung cấp một lần trên mỗi máy.",
    experimental: "Hạ tầng thử nghiệm cho mã bạn sở hữu",
    explore: "Khám phá Coop",
    viewSource: "Xem mã nguồn",
    quickStart: "Bắt đầu nhanh",
    facts: ["Runtime dùng chung", "Một worker cho mỗi triển khai", "Triển khai, kiểm tra và rollback"],
    appLibrary: "Thư viện ứng dụng",
    worker: "Worker Coop",
    sharedProviders: "Runtime + thư viện chuẩn dùng chung",
    onePerMachine: "một trên mỗi máy",
    diagramAria: "Perry biên dịch TypeScript thành thư viện ứng dụng, worker Coop tải nó và kết nối với runtime dùng chung.",
    whyTitle: "Perry biên dịch. Coop giữ cho nó hoạt động.",
    whyBody: "Khác biệt nằm ở nơi runtime ngôn ngữ tồn tại. Coop giữ image ứng dụng nhỏ và cung cấp runtime Perry tương thích cùng thư viện chuẩn ở cấp host.",
    perryTitle: "Một tệp thực thi Perry thông thường",
    perryBody: "Ứng dụng, runtime, bộ thu gom rác và các tính năng thư viện chuẩn được chọn được liên kết vào một tệp thực thi riêng cho đích.",
    coopTitle: "Một triển khai Coop",
    coopBody: "Ứng dụng được biên dịch thành thư viện dùng chung chỉ chứa app. Runtime tương thích được xây dựng một lần trên mỗi máy và danh tính được kiểm tra trước khi ánh xạ ứng dụng.",
    architectureTitle: "Tách theo ranh giới lỗi",
    architectureBody: "Máy, từng triển khai và từng yêu cầu có trách nhiệm riêng. Mã ứng dụng không bao giờ chạy trong daemon của máy.",
    tiers: [
      { title: "Daemon · một trên mỗi máy", body: "Kết thúc TLS, định tuyến theo host và đường dẫn, quản lý triển khai, artifact, API quản trị và metric." },
      { title: "Worker · một trên mỗi triển khai", body: "Tải thư viện ứng dụng, sở hữu trạng thái runtime Perry và chạy cron cùng hàng đợi bền vững." },
      { title: "Lần gọi · một trên mỗi yêu cầu", body: "Chạy như một tác vụ trong worker và chia sẻ không gian địa chỉ mà không tạo tiến trình cho từng yêu cầu." },
    ],
    workingTitle: "Những gì hoạt động hôm nay",
    workingBody: "Coop là hạ tầng đã được kiểm thử nhưng chưa phải sản phẩm lưu trữ hoàn thiện. Bản triển khai hiện tại gồm:",
    workingItems: ["Biên dịch TypeScript, định tuyến HTTP và mount tĩnh", "Kiểm tra danh tính runtime dùng chung", "Triển khai định địa chỉ theo nội dung và rollback", "Cron và hàng đợi bền vững", "KV và lưu trữ đối tượng cho worker riêng", "CLI, metric Prometheus, cảnh báo và dashboard Grafana"],
    developerTitle: "Bề mặt triển khai nhỏ",
    developerBody: "Một triển khai là thư mục có coop.toml và một hoặc nhiều handler. Coop biên dịch, lưu cache kết quả và khởi động worker cục bộ.",
    configLabel: "coop.toml",
    handlerLabel: "handlers/hello.ts",
    runLabel: "Chạy cục bộ",
    fitTitle: "Phạm vi hẹp có chủ đích",
    rightTitle: "Phù hợp hôm nay",
    rightItems: ["Dịch vụ và ứng dụng nhỏ có mã do bạn sở hữu", "Một người vận hành danh mục trên một máy", "Khối lượng công việc biên dịch được trong tập con TypeScript của Perry", "Nhóm coi trọng mật độ, artifact rõ ràng và rollback nhanh"],
    notYetTitle: "Những điều Coop chưa hứa hẹn",
    notYetItems: ["Tương thích tùy ý với npm hoặc Node.js", "Sandbox cho mã bên thứ ba không đáng tin cậy", "Thay thế Kubernetes hoặc nền tảng đa vùng", "Luôn nhanh hơn Node.js"],
    benchmarkTitle: "Mật độ là luận điểm. Benchmark vẫn đang được hoàn thiện.",
    benchmarkBody: "Các phép đo hiện tại cho kết quả khác nhau theo khối lượng công việc. Coop cho thấy mật độ hứa hẹn với ứng dụng Linux nhỏ, trong khi một route Next.js đầy đủ dùng nhiều CPU hơn Node.js ở thử nghiệm khác. Hãy đọc phương pháp trước khi trích dẫn.",
    benchmarks: "Đọc benchmark",
    status: "Xem trạng thái hiện tại",
    closingTitle: "Xây bằng Perry. Chạy trong Coop.",
    closingBody: "Khám phá mã nguồn, chạy triển khai mẫu và góp phần biến mô hình runtime dùng chung thành hạ tầng đáng tin cậy.",
  },
  id: {
    metaTitle: "Coop — Hosting TypeScript native untuk Perry",
    metaDescription: "Coop meng-host aplikasi TypeScript yang dikompilasi Perry dengan runtime bersama, worker deployment terisolasi, dan rollback berbasis alamat konten.",
    adjacent: "Proyek yang berdekatan dengan Perry · Pre-1.0",
    tagline: "Tempat kode Perry beristirahat dan berjalan.",
    intro: "Coop mengubah direktori TypeScript yang kompatibel dengan Perry menjadi pustaka aplikasi native dan menyajikannya lewat HTTP, sementara runtime dan pustaka standar Perry disediakan sekali per mesin.",
    experimental: "Infrastruktur eksperimental untuk kode milik Anda",
    explore: "Jelajahi Coop",
    viewSource: "Lihat sumber",
    quickStart: "Mulai cepat",
    facts: ["Runtime bersama", "Satu worker per deployment", "Deploy, periksa, dan rollback"],
    appLibrary: "Pustaka aplikasi",
    worker: "Worker Coop",
    sharedProviders: "Runtime + pustaka standar bersama",
    onePerMachine: "satu per mesin",
    diagramAria: "Perry mengompilasi TypeScript menjadi pustaka aplikasi, worker Coop memuatnya, lalu menghubungkannya ke runtime bersama.",
    whyTitle: "Perry mengompilasi. Coop menjaganya tetap berjalan.",
    whyBody: "Perbedaannya adalah tempat runtime bahasa berada. Coop menjaga image aplikasi tetap kecil dan menyediakan runtime Perry yang kompatibel beserta pustaka standar di tingkat host.",
    perryTitle: "Executable Perry biasa",
    perryBody: "Aplikasi, runtime, garbage collector, dan fitur pustaka standar terpilih ditautkan ke satu executable khusus target.",
    coopTitle: "Deployment Coop",
    coopBody: "Aplikasi dikompilasi sebagai pustaka bersama yang hanya berisi app. Runtime yang kompatibel dibangun sekali per mesin dan identitasnya diverifikasi sebelum aplikasi dipetakan.",
    architectureTitle: "Dipisahkan menurut batas kegagalan",
    architectureBody: "Mesin, setiap deployment, dan setiap permintaan memiliki tanggung jawab berbeda. Kode aplikasi tidak pernah berjalan di daemon mesin.",
    tiers: [
      { title: "Daemon · satu per mesin", body: "Mengakhiri TLS, merutekan berdasarkan host dan path, serta mengelola deployment, artefak, API admin, dan metrik." },
      { title: "Worker · satu per deployment", body: "Memuat pustaka aplikasi, memiliki status runtime Perry, serta menjalankan cron dan antrean tahan lama." },
      { title: "Invokasi · satu per permintaan", body: "Berjalan sebagai task di dalam worker dan berbagi ruang alamat tanpa membuat proses untuk setiap permintaan." },
    ],
    workingTitle: "Yang bekerja hari ini",
    workingBody: "Coop adalah infrastruktur yang telah diuji, tetapi belum menjadi produk hosting yang selesai. Implementasi saat ini mencakup:",
    workingItems: ["Kompilasi TypeScript, routing HTTP, dan mount statis", "Pemeriksaan identitas runtime bersama", "Deployment berbasis alamat konten dan rollback", "Cron dan antrean tahan lama", "KV dan penyimpanan objek untuk worker khusus", "CLI, metrik Prometheus, peringatan, dan dashboard Grafana"],
    developerTitle: "Permukaan deployment yang kecil",
    developerBody: "Deployment adalah direktori dengan coop.toml dan satu atau beberapa handler. Coop mengompilasinya, menyimpan hasil di cache, dan memulai worker lokal.",
    configLabel: "coop.toml",
    handlerLabel: "handlers/hello.ts",
    runLabel: "Jalankan lokal",
    fitTitle: "Sengaja dibuat sempit",
    rightTitle: "Cocok digunakan hari ini",
    rightItems: ["Layanan dan aplikasi kecil dengan kode milik Anda", "Satu operator menjalankan portofolio pada satu mesin", "Beban kerja yang dapat dikompilasi dalam subset TypeScript Perry", "Tim yang menghargai kepadatan, artefak eksplisit, dan rollback cepat"],
    notYetTitle: "Yang belum dijanjikan Coop",
    notYetItems: ["Kompatibilitas npm atau Node.js secara sembarang", "Sandbox untuk kode pihak ketiga yang tidak tepercaya", "Pengganti Kubernetes atau platform multiwilayah", "Keunggulan kinerja universal atas Node.js"],
    benchmarkTitle: "Kepadatan adalah tesisnya. Benchmark masih terus dikerjakan.",
    benchmarkBody: "Pengukuran saat ini menunjukkan arah berbeda untuk beban kerja berbeda. Coop menunjukkan kepadatan menjanjikan pada aplikasi Linux kecil, sementara route Next.js lengkap memakai lebih banyak CPU daripada Node.js dalam pengujian lain. Baca metodologi sebelum mengutip hasilnya.",
    benchmarks: "Baca benchmark",
    status: "Lihat status saat ini",
    closingTitle: "Bangun dengan Perry. Jalankan di Coop.",
    closingBody: "Jelajahi sumber, jalankan deployment contoh, dan bantu menjadikan model runtime bersama sebagai infrastruktur yang andal.",
  },
  "zh-Hans": {
    metaTitle: "Coop — 面向 Perry 的原生 TypeScript 托管",
    metaDescription: "Coop 托管由 Perry 编译的 TypeScript 应用，提供共享运行时、隔离的部署工作进程以及内容寻址回滚。",
    adjacent: "Perry 相邻项目 · Pre-1.0",
    tagline: "让 Perry 代码安顿并运行的地方。",
    intro: "Coop 将一个兼容 Perry 的 TypeScript 目录编译为原生应用库并通过 HTTP 提供服务，而 Perry 运行时和标准库在每台机器上只需提供一次。",
    experimental: "面向自有代码的实验性基础设施",
    explore: "探索 Coop",
    viewSource: "查看源码",
    quickStart: "快速开始",
    facts: ["共享运行时提供程序", "每个部署一个工作进程", "部署、检查与回滚"],
    appLibrary: "应用库",
    worker: "Coop 工作进程",
    sharedProviders: "共享运行时 + 标准库",
    onePerMachine: "每台机器一个",
    diagramAria: "Perry 将 TypeScript 编译为应用库，Coop 工作进程加载该库并连接共享运行时。",
    whyTitle: "Perry 负责编译，Coop 负责持续运行。",
    whyBody: "区别在于语言运行时所在的位置。Coop 保持应用镜像小巧，并在主机层提供兼容的 Perry 运行时和标准库。",
    perryTitle: "普通的 Perry 可执行文件",
    perryBody: "应用、运行时、垃圾回收器和选定的标准库功能会链接到一个面向目标平台的可执行文件中。",
    coopTitle: "Coop 部署",
    coopBody: "应用被编译为仅包含应用代码的共享库。兼容的提供程序在每台机器上构建一次，并在映射应用前验证其身份。",
    architectureTitle: "按故障边界拆分",
    architectureBody: "机器、每个部署和每个请求都有独立职责。应用代码绝不会在机器守护进程中运行。",
    tiers: [
      { title: "守护进程 · 每台机器一个", body: "终止 TLS，按主机和路径路由，并管理部署、制品、管理 API 和指标。" },
      { title: "工作进程 · 每个部署一个", body: "加载应用库，拥有 Perry 运行时状态，并执行 cron 和持久队列任务。" },
      { title: "调用 · 每个请求一个", body: "作为部署工作进程中的任务运行，共享其地址空间，无需为每个请求创建进程。" },
    ],
    workingTitle: "当前可用的能力",
    workingBody: "Coop 是经过测试的基础设施，但还不是完成的托管产品。当前实现包括：",
    workingItems: ["TypeScript 编译、HTTP 路由和静态挂载", "共享提供程序身份检查", "内容寻址部署和回滚", "Cron 和持久队列", "专用工作进程的 KV 与对象存储", "CLI、Prometheus 指标、告警和 Grafana 仪表板"],
    developerTitle: "精简的部署界面",
    developerBody: "部署是一个包含 coop.toml 和一个或多个处理程序的目录。Coop 会编译它、缓存结果并启动本地工作进程。",
    configLabel: "coop.toml",
    handlerLabel: "handlers/hello.ts",
    runLabel: "本地运行",
    fitTitle: "有意保持聚焦",
    rightTitle: "目前适合的场景",
    rightItems: ["代码由你拥有的服务和小型应用", "单个运维人员在一台机器上运行一组服务", "可在 Perry TypeScript 子集中编译的工作负载", "重视密度、明确制品和快速回滚的团队"],
    notYetTitle: "Coop 尚未承诺的能力",
    notYetItems: ["任意 npm 或 Node.js 兼容性", "面向不受信任第三方代码的沙箱", "取代 Kubernetes 或成为多区域平台", "相对 Node.js 的普遍性能优势"],
    benchmarkTitle: "密度是目标，基准测试仍在推进。",
    benchmarkBody: "当前测量在不同工作负载上呈现不同方向。Coop 在小型 Linux 应用中展现出良好密度，而另一项测试中的完整 Next.js 路由比 Node.js 使用更多 CPU。引用结果前请先阅读测试方法。",
    benchmarks: "阅读基准测试",
    status: "查看当前状态",
    closingTitle: "用 Perry 构建，在 Coop 中运行。",
    closingBody: "探索源码、运行示例部署，并帮助共享运行时模型发展为可靠的基础设施。",
  },
};

export function getCoopContent(locale: string): CoopContent {
  return content[locale as Locale] ?? content.en;
}
