import type { ComponentType } from "react";

export interface LandingMeta {
  /** <title> value; template " — Perry" is appended unless absoluteTitle */
  title: string;
  description: string;
  /** Leaf name used in BreadcrumbList JSON-LD */
  breadcrumb: string;
  /** Set when the title already contains the brand */
  absoluteTitle?: boolean;
}

export interface LandingModule {
  default: ComponentType;
  meta: LandingMeta;
}

type Loader = () => Promise<LandingModule>;

// One entry per locale per slug. Locales without a translation fall back
// to English. Generated by scratchpad/merge_translations.py.
const loaders: Record<string, Record<string, Loader>> = {
  "getting-started": {
    en: () => import("./getting-started/en"),
    de: () => import("./getting-started/de"),
    es: () => import("./getting-started/es"),
    fr: () => import("./getting-started/fr"),
    it: () => import("./getting-started/it"),
    ja: () => import("./getting-started/ja"),
    ko: () => import("./getting-started/ko"),
    pt: () => import("./getting-started/pt"),
    th: () => import("./getting-started/th"),
    tr: () => import("./getting-started/tr"),
    vi: () => import("./getting-started/vi"),
    id: () => import("./getting-started/id"),
    "zh-Hans": () => import("./getting-started/zh-Hans"),
  },
  "compile-typescript-to-binary": {
    en: () => import("./compile-typescript-to-binary/en"),
    de: () => import("./compile-typescript-to-binary/de"),
    es: () => import("./compile-typescript-to-binary/es"),
    fr: () => import("./compile-typescript-to-binary/fr"),
    it: () => import("./compile-typescript-to-binary/it"),
    ja: () => import("./compile-typescript-to-binary/ja"),
    ko: () => import("./compile-typescript-to-binary/ko"),
    pt: () => import("./compile-typescript-to-binary/pt"),
    th: () => import("./compile-typescript-to-binary/th"),
    tr: () => import("./compile-typescript-to-binary/tr"),
    vi: () => import("./compile-typescript-to-binary/vi"),
    id: () => import("./compile-typescript-to-binary/id"),
    "zh-Hans": () => import("./compile-typescript-to-binary/zh-Hans"),
  },
  "typescript-native-compiler": {
    en: () => import("./typescript-native-compiler/en"),
    de: () => import("./typescript-native-compiler/de"),
    es: () => import("./typescript-native-compiler/es"),
    fr: () => import("./typescript-native-compiler/fr"),
    it: () => import("./typescript-native-compiler/it"),
    ja: () => import("./typescript-native-compiler/ja"),
    ko: () => import("./typescript-native-compiler/ko"),
    pt: () => import("./typescript-native-compiler/pt"),
    th: () => import("./typescript-native-compiler/th"),
    tr: () => import("./typescript-native-compiler/tr"),
    vi: () => import("./typescript-native-compiler/vi"),
    id: () => import("./typescript-native-compiler/id"),
    "zh-Hans": () => import("./typescript-native-compiler/zh-Hans"),
  },
  "typescript-llvm": {
    en: () => import("./typescript-llvm/en"),
    de: () => import("./typescript-llvm/de"),
    es: () => import("./typescript-llvm/es"),
    fr: () => import("./typescript-llvm/fr"),
    it: () => import("./typescript-llvm/it"),
    ja: () => import("./typescript-llvm/ja"),
    ko: () => import("./typescript-llvm/ko"),
    pt: () => import("./typescript-llvm/pt"),
    th: () => import("./typescript-llvm/th"),
    tr: () => import("./typescript-llvm/tr"),
    vi: () => import("./typescript-llvm/vi"),
    id: () => import("./typescript-llvm/id"),
    "zh-Hans": () => import("./typescript-llvm/zh-Hans"),
  },
  "perry-vs-electron-alternatives": {
    en: () => import("./perry-vs-electron-alternatives/en"),
    de: () => import("./perry-vs-electron-alternatives/de"),
    es: () => import("./perry-vs-electron-alternatives/es"),
    fr: () => import("./perry-vs-electron-alternatives/fr"),
    it: () => import("./perry-vs-electron-alternatives/it"),
    ja: () => import("./perry-vs-electron-alternatives/ja"),
    ko: () => import("./perry-vs-electron-alternatives/ko"),
    pt: () => import("./perry-vs-electron-alternatives/pt"),
    th: () => import("./perry-vs-electron-alternatives/th"),
    tr: () => import("./perry-vs-electron-alternatives/tr"),
    vi: () => import("./perry-vs-electron-alternatives/vi"),
    id: () => import("./perry-vs-electron-alternatives/id"),
    "zh-Hans": () => import("./perry-vs-electron-alternatives/zh-Hans"),
  },
};

export async function getLandingContent(
  slug: string,
  locale: string
): Promise<LandingModule> {
  const bySlug = loaders[slug];
  const loader = bySlug[locale] ?? bySlug.en;
  return loader();
}
